version: "3.7"
services:

  dev:
    container_name: nestjs-starter_dev
    env_file:
      - .env.local
      - .env.developement.local
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/apps/nestjs-starter
      - /apps/nestjs-starter/node_modules
    environment:
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DB: ${DATABASE_NAME}
    depends_on: 
      - mysql
    ports:
      - ${SERVER_PORT}:3000
    extra_hosts:
      - ${SERVER_HOST}:127.0.0.1
    command: npm run start

  mysql:
      container_name: nestjs-starter-mysql
      image: mysql:8.0
      volumes:
        - nestjs-starter-mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_PORT: ${DATABASE_PORT}

volumes:
  nestjs-starter-mysql: